# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Academic
    url: /categories/academic/
    weight: 20
  - name: Journal
    url: /categories/journal/
    weight: 30
  - name: Topics
    url: tags/
    weight: 40
# - name: Uses
#   url: uses/
#   weight: 30
